"""add reaction temperature and time

Revision ID: a05439f9dd64
Revises: 309e42d7c6fc
Create Date: 2026-07-25 18:13:25.057676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a05439f9dd64'
down_revision: Union[str, Sequence[str], None] = '309e42d7c6fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reactions', sa.Column('temperature', sa.Float(), nullable=True))
    op.add_column('reactions', sa.Column('duration_h', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reactions', 'duration_h')
    op.drop_column('reactions', 'temperature')
    # ### end Alembic commands ###
