"""reactionsにtitle列を追加

Revision ID: d7f172f35247
Revises: a05439f9dd64
Create Date: 2026-08-20 23:50:35.993968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7f172f35247'
down_revision: Union[str, Sequence[str], None] = 'a05439f9dd64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reactions', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reactions', 'title')
    # ### end Alembic commands ###
