from typing import Any

class MolDraw2DSVG:
    def __init__(self, width: int, height: int) -> None: ...
    def DrawMolecule(self, mol: Any) -> None: ...
    def DrawReaction(self, rxn: Any) -> None: ...
    def FinishDrawing(self) -> None: ...
    def GetDrawingText(self) -> str: ...
